# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
 name = "研究"
 pageRef = "research"
 weight = 10

[[main]]
 name = "碩士論文"
 parent = "研究"
 pageRef = "thesis"
 weight = 20

[[main]]
 name = "專案"
 pageRef = "projects"
 weight = 20

[[main]]
 name = "能源交易"
 parent = "專案"
 pageRef = "energy-trading"
 weight = 20

[[main]]
 name = "智慧控制"
 parent = "專案"
 pageRef = "smart-control"
 weight = 20

[[main]]
  name = "學習"
  pageRef = "learn"
  weight = 30

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 35

[[main]]
  name = "開源"
  pageRef = "open-source"
  weight = 40

[[main]]
  pre = "github"
  url = "https://github.com/ttw225"
  weight = 50


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "標籤"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "分類"
  pageRef = "categories"
  weight = 20
